# compose 파일 버전
version: '3'
services:
    mysql:
        image: mysql:8.1
        restart: always
        container_name: mysql
        ports:
          - "3333:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./data/mysql/:/var/lib/mysql